package com.web.form.report.reportconfig;

import com.web.form.base.BaseForm;

public class t_report_rp_query extends BaseForm implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.QUERY_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private Integer query_id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private Integer report_id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.F_CHN
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String fChn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.F_ENG
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String fEng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.INPUT_TYPE
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String inputType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.IS_NEED
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String isNeed;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private Short priority;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.OUT_KEY_NAME
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String outKeyName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.QUERY_DOMAINS
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String queryDomains;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_QUERY.SP_DATA
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    private String spData;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.QUERY_ID
     *
     * @return the value of T_REPORT_RP_QUERY.QUERY_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public Integer getquery_id() {
        return query_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.QUERY_ID
     *
     * @param query_id the value for T_REPORT_RP_QUERY.QUERY_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setquery_id(Integer query_id) {
        this.query_id = query_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.REPORT_ID
     *
     * @return the value of T_REPORT_RP_QUERY.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public Integer getreport_id() {
        return report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.REPORT_ID
     *
     * @param report_id the value for T_REPORT_RP_QUERY.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setreport_id(Integer report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.F_CHN
     *
     * @return the value of T_REPORT_RP_QUERY.F_CHN
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getfChn() {
        return fChn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.F_CHN
     *
     * @param fChn the value for T_REPORT_RP_QUERY.F_CHN
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setfChn(String fChn) {
        this.fChn = fChn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.F_ENG
     *
     * @return the value of T_REPORT_RP_QUERY.F_ENG
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getfEng() {
        return fEng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.F_ENG
     *
     * @param fEng the value for T_REPORT_RP_QUERY.F_ENG
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setfEng(String fEng) {
        this.fEng = fEng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.INPUT_TYPE
     *
     * @return the value of T_REPORT_RP_QUERY.INPUT_TYPE
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.INPUT_TYPE
     *
     * @param inputType the value for T_REPORT_RP_QUERY.INPUT_TYPE
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setInputType(String inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.IS_NEED
     *
     * @return the value of T_REPORT_RP_QUERY.IS_NEED
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getIsNeed() {
        return isNeed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.IS_NEED
     *
     * @param isNeed the value for T_REPORT_RP_QUERY.IS_NEED
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setIsNeed(String isNeed) {
        this.isNeed = isNeed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.PRIORITY
     *
     * @return the value of T_REPORT_RP_QUERY.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.PRIORITY
     *
     * @param priority the value for T_REPORT_RP_QUERY.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setPriority(Short priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.OUT_KEY_NAME
     *
     * @return the value of T_REPORT_RP_QUERY.OUT_KEY_NAME
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getOutKeyName() {
        return outKeyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.OUT_KEY_NAME
     *
     * @param outKeyName the value for T_REPORT_RP_QUERY.OUT_KEY_NAME
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setOutKeyName(String outKeyName) {
        this.outKeyName = outKeyName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.QUERY_DOMAINS
     *
     * @return the value of T_REPORT_RP_QUERY.QUERY_DOMAINS
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getQueryDomains() {
        return queryDomains;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.QUERY_DOMAINS
     *
     * @param queryDomains the value for T_REPORT_RP_QUERY.QUERY_DOMAINS
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setQueryDomains(String queryDomains) {
        this.queryDomains = queryDomains;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_QUERY.SP_DATA
     *
     * @return the value of T_REPORT_RP_QUERY.SP_DATA
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public String getSpData() {
        return spData;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_QUERY.SP_DATA
     *
     * @param spData the value for T_REPORT_RP_QUERY.SP_DATA
     *
     * @ibatorgenerated Sat Jul 24 11:55:43 CST 2010
     */
    public void setSpData(String spData) {
        this.spData = spData;
    }
    
    /*数据字典*/
    private String isNeeddesc;
    private String inputTypedesc;

	public String getIsNeeddesc() {
		return isNeeddesc;
	}

	public void setIsNeeddesc(String isNeeddesc) {
		this.isNeeddesc = isNeeddesc;
	}

	public String getInputTypedesc() {
		return inputTypedesc;
	}

	public void setInputTypedesc(String inputTypedesc) {
		this.inputTypedesc = inputTypedesc;
	}
    
    
}