package com.web.form.report.reportconfig;

import com.web.form.base.BaseForm;

public class t_report_outkeytb extends BaseForm implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_OUTKEYTB.OUTKEYID
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    private Integer outkeyid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_OUTKEYTB.OUTKEYNAME
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    private String outkeyname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_OUTKEYTB.OUTKEYTABLE
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    private String outkeytable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_OUTKEYTB.OUTKEYSQL
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    private String outkeysql;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_OUTKEYTB.OUTKEYDESC
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    private String outkeydesc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_OUTKEYTB.OUTKEYID
     *
     * @return the value of T_REPORT_OUTKEYTB.OUTKEYID
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public Integer getOutkeyid() {
        return outkeyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_OUTKEYTB.OUTKEYID
     *
     * @param outkeyid the value for T_REPORT_OUTKEYTB.OUTKEYID
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public void setOutkeyid(Integer outkeyid) {
        this.outkeyid = outkeyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_OUTKEYTB.OUTKEYNAME
     *
     * @return the value of T_REPORT_OUTKEYTB.OUTKEYNAME
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public String getOutkeyname() {
        return outkeyname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_OUTKEYTB.OUTKEYNAME
     *
     * @param outkeyname the value for T_REPORT_OUTKEYTB.OUTKEYNAME
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public void setOutkeyname(String outkeyname) {
        this.outkeyname = outkeyname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_OUTKEYTB.OUTKEYTABLE
     *
     * @return the value of T_REPORT_OUTKEYTB.OUTKEYTABLE
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public String getOutkeytable() {
        return outkeytable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_OUTKEYTB.OUTKEYTABLE
     *
     * @param outkeytable the value for T_REPORT_OUTKEYTB.OUTKEYTABLE
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public void setOutkeytable(String outkeytable) {
        this.outkeytable = outkeytable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_OUTKEYTB.OUTKEYSQL
     *
     * @return the value of T_REPORT_OUTKEYTB.OUTKEYSQL
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public String getOutkeysql() {
        return outkeysql;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_OUTKEYTB.OUTKEYSQL
     *
     * @param outkeysql the value for T_REPORT_OUTKEYTB.OUTKEYSQL
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public void setOutkeysql(String outkeysql) {
        this.outkeysql = outkeysql;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_OUTKEYTB.OUTKEYDESC
     *
     * @return the value of T_REPORT_OUTKEYTB.OUTKEYDESC
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public String getOutkeydesc() {
        return outkeydesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_OUTKEYTB.OUTKEYDESC
     *
     * @param outkeydesc the value for T_REPORT_OUTKEYTB.OUTKEYDESC
     *
     * @ibatorgenerated Sat Jul 24 12:32:21 CST 2010
     */
    public void setOutkeydesc(String outkeydesc) {
        this.outkeydesc = outkeydesc;
    }
}