package com.web.form.report.reportconfig;

import com.web.form.base.BaseForm;

public class t_report_rp_column  extends BaseForm implements java.io.Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.COLUMN_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private Integer column_id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private Integer report_id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.COLUMN_NAME
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String columnName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.ALIGN
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String align;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String fontColor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String bgColor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.MERGED
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String merged;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.ROLLUP_TYPE
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String rollupType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.MERGED_FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String mergedFontColor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.MERGED_BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String mergedBgColor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private Integer priority;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_COLUMN.IS_LAST_ROW_SHOW
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    private String isLastRowShow;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.COLUMN_ID
     *
     * @return the value of T_REPORT_RP_COLUMN.COLUMN_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public Integer getcolumn_id() {
        return column_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.COLUMN_ID
     *
     * @param column_id the value for T_REPORT_RP_COLUMN.COLUMN_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setcolumn_id(Integer column_id) {
        this.column_id = column_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.REPORT_ID
     *
     * @return the value of T_REPORT_RP_COLUMN.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public Integer getreport_id() {
        return report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.REPORT_ID
     *
     * @param report_id the value for T_REPORT_RP_COLUMN.REPORT_ID
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setreport_id(Integer report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.COLUMN_NAME
     *
     * @return the value of T_REPORT_RP_COLUMN.COLUMN_NAME
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.COLUMN_NAME
     *
     * @param columnName the value for T_REPORT_RP_COLUMN.COLUMN_NAME
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.ALIGN
     *
     * @return the value of T_REPORT_RP_COLUMN.ALIGN
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getAlign() {
        return align;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.ALIGN
     *
     * @param align the value for T_REPORT_RP_COLUMN.ALIGN
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setAlign(String align) {
        this.align = align;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.FONT_COLOR
     *
     * @return the value of T_REPORT_RP_COLUMN.FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getFontColor() {
        return fontColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.FONT_COLOR
     *
     * @param fontColor the value for T_REPORT_RP_COLUMN.FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setFontColor(String fontColor) {
        this.fontColor = fontColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.BG_COLOR
     *
     * @return the value of T_REPORT_RP_COLUMN.BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.BG_COLOR
     *
     * @param bgColor the value for T_REPORT_RP_COLUMN.BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.MERGED
     *
     * @return the value of T_REPORT_RP_COLUMN.MERGED
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getMerged() {
        return merged;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.MERGED
     *
     * @param merged the value for T_REPORT_RP_COLUMN.MERGED
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setMerged(String merged) {
        this.merged = merged;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.ROLLUP_TYPE
     *
     * @return the value of T_REPORT_RP_COLUMN.ROLLUP_TYPE
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getRollupType() {
        return rollupType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.ROLLUP_TYPE
     *
     * @param rollupType the value for T_REPORT_RP_COLUMN.ROLLUP_TYPE
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setRollupType(String rollupType) {
        this.rollupType = rollupType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.MERGED_FONT_COLOR
     *
     * @return the value of T_REPORT_RP_COLUMN.MERGED_FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getMergedFontColor() {
        return mergedFontColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.MERGED_FONT_COLOR
     *
     * @param mergedFontColor the value for T_REPORT_RP_COLUMN.MERGED_FONT_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setMergedFontColor(String mergedFontColor) {
        this.mergedFontColor = mergedFontColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.MERGED_BG_COLOR
     *
     * @return the value of T_REPORT_RP_COLUMN.MERGED_BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getMergedBgColor() {
        return mergedBgColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.MERGED_BG_COLOR
     *
     * @param mergedBgColor the value for T_REPORT_RP_COLUMN.MERGED_BG_COLOR
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setMergedBgColor(String mergedBgColor) {
        this.mergedBgColor = mergedBgColor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.PRIORITY
     *
     * @return the value of T_REPORT_RP_COLUMN.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.PRIORITY
     *
     * @param priority the value for T_REPORT_RP_COLUMN.PRIORITY
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_COLUMN.IS_LAST_ROW_SHOW
     *
     * @return the value of T_REPORT_RP_COLUMN.IS_LAST_ROW_SHOW
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public String getIsLastRowShow() {
        return isLastRowShow;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_COLUMN.IS_LAST_ROW_SHOW
     *
     * @param isLastRowShow the value for T_REPORT_RP_COLUMN.IS_LAST_ROW_SHOW
     *
     * @ibatorgenerated Sat Jul 24 12:21:39 CST 2010
     */
    public void setIsLastRowShow(String isLastRowShow) {
        this.isLastRowShow = isLastRowShow;
    }
    


    /*数据字典*/
    private String isLastRowShowdesc;
    private String aligndesc;
    private String fontColordesc;
    private String bgColordesc;
    private String mergeddesc;
    private String rollupTypedesc;
    private String mergedFontColordesc;
    private String mergedBgColordesc;

	public String getIsLastRowShowdesc() {
		return isLastRowShowdesc;
	}

	public void setIsLastRowShowdesc(String isLastRowShowdesc) {
		this.isLastRowShowdesc = isLastRowShowdesc;
	}

	public String getAligndesc() {
		return aligndesc;
	}

	public void setAligndesc(String aligndesc) {
		this.aligndesc = aligndesc;
	}

	public String getFontColordesc() {
		return fontColordesc;
	}

	public void setFontColordesc(String fontColordesc) {
		this.fontColordesc = fontColordesc;
	}

	public String getBgColordesc() {
		return bgColordesc;
	}

	public void setBgColordesc(String bgColordesc) {
		this.bgColordesc = bgColordesc;
	}

	public String getMergeddesc() {
		return mergeddesc;
	}

	public void setMergeddesc(String mergeddesc) {
		this.mergeddesc = mergeddesc;
	}

	public String getRollupTypedesc() {
		return rollupTypedesc;
	}

	public void setRollupTypedesc(String rollupTypedesc) {
		this.rollupTypedesc = rollupTypedesc;
	}

	public String getMergedFontColordesc() {
		return mergedFontColordesc;
	}

	public void setMergedFontColordesc(String mergedFontColordesc) {
		this.mergedFontColordesc = mergedFontColordesc;
	}

	public String getMergedBgColordesc() {
		return mergedBgColordesc;
	}

	public void setMergedBgColordesc(String mergedBgColordesc) {
		this.mergedBgColordesc = mergedBgColordesc;
	}
    
    
}