package com.web.form.report.reportconfig;

import java.util.Date;

import com.web.form.base.BaseForm;

public class t_report_rp_base extends BaseForm implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
    private Integer report_id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.REPORT_NAME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String reportName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.NEED_FORMAT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String needFormat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.NEED_HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String needHeader;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String header;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.HAS_SEQ
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String hasSeq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.SQL
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String sql;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.STATUS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.IS_EXTEND
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String isExtend;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.EXTEND_CLASS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String extendClass;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.CREATE_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String createUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.CREATE_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.LAST_MODIFY_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String lastModifyUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.LAST_MODIFY_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String lastModifyTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.NOTES
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String notes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.RESV_FLD1
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
//    private String resvFld1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.RESV_FLD2
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
//    private String resvFld2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.QUERY_DOMAIN_COUNT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private Short queryDomainCount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.SHORT_ENG
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String shortEng;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column T_REPORT_RP_BASE.NEED_BATCH_NO
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    private String needBatchNo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.REPORT_ID
     *
     * @return the value of T_REPORT_RP_BASE.REPORT_ID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public Integer getreport_id() {
        return report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.REPORT_ID
     *
     * @param report_id the value for T_REPORT_RP_BASE.REPORT_ID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setreport_id(Integer report_id) {
        this.report_id = report_id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.REPORT_NAME
     *
     * @return the value of T_REPORT_RP_BASE.REPORT_NAME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.REPORT_NAME
     *
     * @param reportName the value for T_REPORT_RP_BASE.REPORT_NAME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.NEED_FORMAT
     *
     * @return the value of T_REPORT_RP_BASE.NEED_FORMAT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getNeedFormat() {
        return needFormat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.NEED_FORMAT
     *
     * @param needFormat the value for T_REPORT_RP_BASE.NEED_FORMAT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setNeedFormat(String needFormat) {
        this.needFormat = needFormat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.NEED_HEADER
     *
     * @return the value of T_REPORT_RP_BASE.NEED_HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getNeedHeader() {
        return needHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.NEED_HEADER
     *
     * @param needHeader the value for T_REPORT_RP_BASE.NEED_HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setNeedHeader(String needHeader) {
        this.needHeader = needHeader;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.HEADER
     *
     * @return the value of T_REPORT_RP_BASE.HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.HEADER
     *
     * @param header the value for T_REPORT_RP_BASE.HEADER
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setHeader(String header) {
        this.header = header;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.HAS_SEQ
     *
     * @return the value of T_REPORT_RP_BASE.HAS_SEQ
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getHasSeq() {
        return hasSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.HAS_SEQ
     *
     * @param hasSeq the value for T_REPORT_RP_BASE.HAS_SEQ
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setHasSeq(String hasSeq) {
        this.hasSeq = hasSeq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.SQL
     *
     * @return the value of T_REPORT_RP_BASE.SQL
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getSql() {
        return sql;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.SQL
     *
     * @param sql the value for T_REPORT_RP_BASE.SQL
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setSql(String sql) {
        this.sql = sql;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.STATUS
     *
     * @return the value of T_REPORT_RP_BASE.STATUS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.STATUS
     *
     * @param status the value for T_REPORT_RP_BASE.STATUS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.IS_EXTEND
     *
     * @return the value of T_REPORT_RP_BASE.IS_EXTEND
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getIsExtend() {
        return isExtend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.IS_EXTEND
     *
     * @param isExtend the value for T_REPORT_RP_BASE.IS_EXTEND
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setIsExtend(String isExtend) {
        this.isExtend = isExtend;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.EXTEND_CLASS
     *
     * @return the value of T_REPORT_RP_BASE.EXTEND_CLASS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getExtendClass() {
        return extendClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.EXTEND_CLASS
     *
     * @param extendClass the value for T_REPORT_RP_BASE.EXTEND_CLASS
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setExtendClass(String extendClass) {
        this.extendClass = extendClass;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.CREATE_UID
     *
     * @return the value of T_REPORT_RP_BASE.CREATE_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.CREATE_UID
     *
     * @param createUid the value for T_REPORT_RP_BASE.CREATE_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.CREATE_TIME
     *
     * @return the value of T_REPORT_RP_BASE.CREATE_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.CREATE_TIME
     *
     * @param createTime the value for T_REPORT_RP_BASE.CREATE_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.LAST_MODIFY_UID
     *
     * @return the value of T_REPORT_RP_BASE.LAST_MODIFY_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getLastModifyUid() {
        return lastModifyUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.LAST_MODIFY_UID
     *
     * @param lastModifyUid the value for T_REPORT_RP_BASE.LAST_MODIFY_UID
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setLastModifyUid(String lastModifyUid) {
        this.lastModifyUid = lastModifyUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.LAST_MODIFY_TIME
     *
     * @return the value of T_REPORT_RP_BASE.LAST_MODIFY_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for T_REPORT_RP_BASE.LAST_MODIFY_TIME
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setLastModifyTime(String lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.NOTES
     *
     * @return the value of T_REPORT_RP_BASE.NOTES
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.NOTES
     *
     * @param notes the value for T_REPORT_RP_BASE.NOTES
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.RESV_FLD1
     *
     * @return the value of T_REPORT_RP_BASE.RESV_FLD1
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
//    public String getResvFld1() {
//        return resvFld1;
//    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.RESV_FLD1
     *
     * @param resvFld1 the value for T_REPORT_RP_BASE.RESV_FLD1
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
//    public void setResvFld1(String resvFld1) {
//        this.resvFld1 = resvFld1;
//    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.RESV_FLD2
     *
     * @return the value of T_REPORT_RP_BASE.RESV_FLD2
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    /**public String getResvFld2() {
       * return resvFld2;
    *}
*/
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.RESV_FLD2
     *
     * @param resvFld2 the value for T_REPORT_RP_BASE.RESV_FLD2
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
   /** public void setResvFld2(String resvFld2) {
    *  this.resvFld2 = resvFld2;
    * }
    */
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.QUERY_DOMAIN_COUNT
     *
     * @return the value of T_REPORT_RP_BASE.QUERY_DOMAIN_COUNT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public Short getQueryDomainCount() {
        return queryDomainCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.QUERY_DOMAIN_COUNT
     *
     * @param queryDomainCount the value for T_REPORT_RP_BASE.QUERY_DOMAIN_COUNT
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setQueryDomainCount(Short queryDomainCount) {
        this.queryDomainCount = queryDomainCount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.SHORT_ENG
     *
     * @return the value of T_REPORT_RP_BASE.SHORT_ENG
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getShortEng() {
        return shortEng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.SHORT_ENG
     *
     * @param shortEng the value for T_REPORT_RP_BASE.SHORT_ENG
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setShortEng(String shortEng) {
        this.shortEng = shortEng;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column T_REPORT_RP_BASE.NEED_BATCH_NO
     *
     * @return the value of T_REPORT_RP_BASE.NEED_BATCH_NO
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public String getNeedBatchNo() {
        return needBatchNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column T_REPORT_RP_BASE.NEED_BATCH_NO
     *
     * @param needBatchNo the value for T_REPORT_RP_BASE.NEED_BATCH_NO
     *
     * @ibatorgenerated Thu Jul 22 13:37:09 CST 2010
     */
    public void setNeedBatchNo(String needBatchNo) {
        this.needBatchNo = needBatchNo;
    }

    
    /*日期转换*/
    private String createtimetrans;
    private String lastmodifytimetrans;

	public String getCreatetimetrans() {
		return createtimetrans;
	}

	public void setCreatetimetrans(String createtimetrans) {
		this.createtimetrans = createtimetrans;
	}

	public String getLastmodifytimetrans() {
		return lastmodifytimetrans;
	}

	public void setLastmodifytimetrans(String lastmodifytimetrans) {
		this.lastmodifytimetrans = lastmodifytimetrans;
	}
	
	/*数据字典*/
	
	private String need_batch_nodesc;
	private String need_formatdesc;
	private String need_headerdesc;
	private String has_seqdesc;
	private String is_extenddesc;
	private String statusdesc;
	private String lastModifyUiddesc;
	private String createUiddesc;
	

	public Integer getReport_id() {
		return report_id;
	}

	public void setReport_id(Integer reportId) {
		report_id = reportId;
	}

	public String getLastModifyUiddesc() {
		return lastModifyUiddesc;
	}

	public void setLastModifyUiddesc(String lastModifyUiddesc) {
		this.lastModifyUiddesc = lastModifyUiddesc;
	}

	public String getCreateUiddesc() {
		return createUiddesc;
	}

	public void setCreateUiddesc(String createUiddesc) {
		this.createUiddesc = createUiddesc;
	}

	public String getNeed_batch_nodesc() {
		return need_batch_nodesc;
	}

	public void setNeed_batch_nodesc(String needBatchNodesc) {
		need_batch_nodesc = needBatchNodesc;
	}

	public String getNeed_formatdesc() {
		return need_formatdesc;
	}

	public void setNeed_formatdesc(String needFormatdesc) {
		need_formatdesc = needFormatdesc;
	}

	public String getNeed_headerdesc() {
		return need_headerdesc;
	}

	public void setNeed_headerdesc(String needHeaderdesc) {
		need_headerdesc = needHeaderdesc;
	}

	public String getHas_seqdesc() {
		return has_seqdesc;
	}

	public void setHas_seqdesc(String hasSeqdesc) {
		has_seqdesc = hasSeqdesc;
	}

	public String getIs_extenddesc() {
		return is_extenddesc;
	}

	public void setIs_extenddesc(String isExtenddesc) {
		is_extenddesc = isExtenddesc;
	}

	public String getStatusdesc() {
		return statusdesc;
	}

	public void setStatusdesc(String statusdesc) {
		this.statusdesc = statusdesc;
	}
	
//	private int reportd;
//
//	public int getReportd() {
//		return reportd;
//	}
//
//	public void setReportd(int reportd) {
//		this.reportd = reportd;
//	}
	
	
	
}
